// <auto-generated />
using System;
using Aura.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aura.Core.Migrations
{
    [DbContext(typeof(AuraDbContext))]
    partial class AuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("Aura.Core.Entities.Constellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DominantEssence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("OverallCohesionScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Constellations");
                });

            modelBuilder.Entity("Aura.Core.Entities.Relationship", b =>
                {
                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("TEXT");

                    b.Property<float>("ConnectionStrength")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SourceNodeId", "TargetNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Aura.Core.Entities.ThoughtNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Essence")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FulfillmentScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsOrbiting")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ThoughtNodes");
                });

            modelBuilder.Entity("Aura.Core.Entities.Constellation", b =>
                {
                    b.OwnsOne("Aura.Core.Entities.AuraVector3", "CenterOfMass", b1 =>
                        {
                            b1.Property<Guid>("ConstellationId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("ConstellationId");

                            b1.ToTable("Constellations");

                            b1.WithOwner()
                                .HasForeignKey("ConstellationId");
                        });

                    b.Navigation("CenterOfMass")
                        .IsRequired();
                });

            modelBuilder.Entity("Aura.Core.Entities.Relationship", b =>
                {
                    b.HasOne("Aura.Core.Entities.ThoughtNode", "SourceNode")
                        .WithMany("Connections")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aura.Core.Entities.ThoughtNode", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Aura.Core.Entities.ThoughtNode", b =>
                {
                    b.OwnsOne("Aura.Core.Entities.AuraVector3", "DailyHomePosition", b1 =>
                        {
                            b1.Property<Guid>("ThoughtNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("ThoughtNodeId");

                            b1.ToTable("ThoughtNodes");

                            b1.WithOwner()
                                .HasForeignKey("ThoughtNodeId");
                        });

                    b.Navigation("DailyHomePosition")
                        .IsRequired();
                });

            modelBuilder.Entity("Aura.Core.Entities.ThoughtNode", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
